const types = {
    ONSNACK: 'ONSNACK',
    
    ONLOADER: 'ONLOADER',

    SIGNUP: 'SIGNUP',
    SIGNUPACCESS: 'SIGNUPACCESS',

    SIGNIN: 'SIGNIN',
    SIGNINSUCCESS: 'SIGNINSUCCESS',
    SIGNINFAILURE: 'SIGNINFAILURE',

    SIGNOUT: 'SIGNOUT',
    SIGNOUTSUCCESS: 'SIGNOUTSUCCESS',
    SIGNOUTFAILURE: 'SIGNOUTFAILURE',

    ISLOGGEDIN: 'ISLOGGEDIN',
    ISLOGGEDINSUCCESS: 'ISLOGGEDINSUCCESS',
    ISLOGGEDINFAILURE: 'ISLOGGEDINFAILURE',

    PRODUCTSAVE: 'PRODUCTSAVE',
    PRODUCTSAVESUCCESS: 'PRODUCTSAVESUCCESS',
    PRODUCTSAVEFAILURE: 'PRODUCTSAVEFAILURE',
    
    GETPRODUCT: 'GETPRODUCT',
    GETPRODUCTSUCCESS: 'GETPRODUCTSUCCESS',
    GETPRODUCTFAILURE: 'GETPRODUCTFAILURE',

    UPDATEPRODUCT: 'UPDATEPRODUCT',
    UPDATEPRODUCTSUCCESS: 'UPDATEPRODUCTSUCCESS',
    UPDATEPRODUCTFAILURE: 'UPDATEPRODUCTFAILURE',
    
    DELETEPRODUCT: 'DELETEPRODUCT',
    DELETEPRODUCTSUCCESS: 'DELETEPRODUCTSUCCESS',
    DELETEPRODUCTFAILURE: 'DELETEPRODUCTFAILURE',

    VENDORSAVE: 'VENDORSAVE',
    VENDORSAVESUCCESS: 'VENDORSAVESUCCESS',
    VENDORSAVEFAILURE: 'VENDORSAVEFAILURE',
    
    GETVENDOR: 'GETVENDOR',
    GETVENDORSUCCESS: 'GETVENDORSUCCESS',
    GETVENDORFAILURE: 'GETVENDORFAILURE',

    UPDATEVENDOR: 'UPDATEVENDOR',
    UPDATEVENDORSUCCESS: 'UPDATEVENDORSUCCESS',
    UPDATEVENDORFAILURE: 'UPDATEVENDORFAILURE',
    
    DELETEVENDOR: 'DELETEVENDOR',
    DELETEVENDORSUCCESS: 'DELETEVENDORSUCCESS',
    DELETEVENDORFAILURE: 'DELETEVENDORFAILURE',

    CLIENTSAVE: 'CLIENTSAVE',
    CLIENTSAVESUCCESS: 'CLIENTSAVESUCCESS',
    CLIENTSAVEFAILURE: 'CLIENTSAVEFAILURE',
    
    GETCLIENT: 'GETCLIENT',
    GETCLIENTSUCCESS: 'GETCLIENTSUCCESS',
    GETCLIENTFAILURE: 'GETCLIENTFAILURE',

    UPDATECLIENT: 'UPDATECLIENT',
    UPDATECLIENTSUCCESS: 'UPDATECLIENTSUCCESS',
    UPDATECLIENTFAILURE: 'UPDATECLIENTFAILURE',
    
    DELETECLIENT: 'DELETECLIENT',
    DELETECLIENTSUCCESS: 'DELETECLIENTSUCCESS',
    DELETECLIENTFAILURE: 'DELETECLIENTFAILURE',
    
    PURCHASESAVE: 'PURCHASESAVE',
    PURCHASESAVESUCCESS: 'PURCHASESAVESUCCESS',
    PURCHASESAVEFAILURE: 'PURCHASESAVEFAILURE',
    
    GETPURCHASE: 'GETPURCHASE',
    GETPURCHASESUCCESS: 'GETPURCHASESUCCESS',
    GETPURCHASEFAILURE: 'GETPURCHASEFAILURE',
    
    UPDATEPURCHASE: 'UPDATEPURCHASE',
    UPDATEPURCHASESUCCESS: 'UPDATEPURCHASESUCCESS',
    UPDATEPURCHASEFAILURE: 'UPDATEPURCHASEFAILURE',
    
    DELETEPURCHASE: 'DELETEPURCHASE',
    DELETEPURCHASESUCCESS: 'DELETEPURCHASESUCCESS',
    DELETEPURCHASEFAILURE: 'DELETEPURCHASEFAILURE',
    
    SALESAVE: 'SALESAVE',
    SALESAVESUCCESS: 'SALESAVESUCCESS',
    SALESAVEFAILURE: 'SALESAVEFAILURE',
    
    GETSALE: 'GETSALE',
    GETSALESUCCESS: 'GETSALESUCCESS',
    GETSALEFAILURE: 'GETSALEFAILURE',
    
    UPDATESALE: 'UPDATESALE',
    UPDATESALESUCCESS: 'UPDATESALESUCCESS',
    UPDATESALEFAILURE: 'UPDATESALEFAILURE',
    
    DELETESALE: 'DELETESALE',
    DELETESALESUCCESS: 'DELETESALESUCCESS',
    DELETESALEFAILURE: 'DELETESALEFAILURE',
    
    PAYMENTSAVE: 'PAYMENTSAVE',
    PAYMENTSAVESUCCESS: 'PAYMENTSAVESUCCESS',
    PAYMENTSAVEFAILURE: 'PAYMENTSAVEFAILURE',
    
    GETPAYMENT: 'GETPAYMENT',
    GETPAYMENTSUCCESS: 'GETPAYMENTSUCCESS',
    GETPAYMENTFAILURE: 'GETPAYMENTFAILURE',
    
    UPDATEPAYMENT: 'UPDATEPAYMENT',
    UPDATEPAYMENTSUCCESS: 'UPDATEPAYMENTSUCCESS',
    UPDATEPAYMENTFAILURE: 'UPDATEPAYMENTFAILURE',
    
    DELETEPAYMENT: 'DELETEPAYMENT',
    DELETEPAYMENTSUCCESS: 'DELETEPAYMENTSUCCESS',
    DELETEPAYMENTFAILURE: 'DELETEPAYMENTFAILURE',
    
    RECOVERYSAVE: 'RECOVERYSAVE',
    RECOVERYSAVESUCCESS: 'RECOVERYSAVESUCCESS',
    RECOVERYSAVEFAILURE: 'RECOVERYSAVEFAILURE',
    
    GETRECOVERY: 'GETRECOVERY',
    GETRECOVERYSUCCESS: 'GETRECOVERYSUCCESS',
    GETRECOVERYFAILURE: 'GETRECOVERYFAILURE',
    
    UPDATERECOVERY: 'UPDATERECOVERY',
    UPDATERECOVERYSUCCESS: 'UPDATERECOVERYSUCCESS',
    UPDATERECOVERYFAILURE: 'UPDATERECOVERYFAILURE',
    
    DELETERECOVERY: 'DELETERECOVERY',
    DELETERECOVERYSUCCESS: 'DELETERECOVERYSUCCESS',
    DELETERECOVERYFAILURE: 'DELETERECOVERYFAILURE',
};

export default types;