const types = {
    ONSNACK: 'ONSNACK',

    SIGNUP: 'SIGNUP',
    SIGNUPACCESS: 'SIGNUPACCESS',

    SIGNIN: 'SIGNIN',
    SIGNINSUCCESS: 'SIGNINSUCCESS',
    SIGNINFAILURE: 'SIGNINFAILURE',

    ISLOGGEDIN: 'ISLOGGEDIN',
    ISLOGGEDINSUCCESS: 'ISLOGGEDINSUCCESS',
    ISLOGGEDINFAILURE: 'ISLOGGEDINFAILURE',

    PRODUCTSAVE: 'PRODUCTSAVE',
    PRODUCTSAVESUCCESS: 'PRODUCTSAVESUCCESS',
    PRODUCTSAVEFAILURE: 'PRODUCTSAVEFAILURE',
};

export default types;